# Generated by Django 4.2.29 on 2026-03-24 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_application_project_vacancy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('negotiation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='proposed_price',
            new_name='proposed_budget',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='delivery_days',
            new_name='proposed_days',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='is_accepted',
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Matn'), ('system', 'Tizim'), ('offer', 'Taklif')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul'), ('rejected', 'Rad')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='ProjectChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_type', models.CharField(choices=[('company_pm', 'Kompaniya — PM'), ('pm_workers', 'PM — Workerlar')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='marketplace.project')),
            ],
            options={
                'verbose_name': 'Loyiha chati',
                'verbose_name_plural': 'Loyiha chatlari',
                'unique_together': {('project', 'chat_type')},
            },
        ),
        migrations.CreateModel(
            name='NegotiationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi'), ('cancelled', 'Bekor')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_negotiations', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_rooms', to='marketplace.vacancy')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_negotiations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Muzokaralar xonasi',
                'unique_together': {('vacancy', 'worker')},
            },
        ),
        migrations.CreateModel(
            name='NegotiationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'Matn'), ('offer', 'Taklif'), ('system', 'Tizim')], default='text', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='negotiation.negotiationroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='negotiation.projectchat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='negotiation.negotiationroom'),
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
