# Generated by Django 4.2.29 on 2026-03-24 00:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(help_text='1 dan 5 gacha baho', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('communication_score', models.IntegerField(default=5, help_text='Muloqot sifati', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('quality_score', models.IntegerField(default=5, help_text='Ish sifati', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('deadline_score', models.IntegerField(default=5, help_text='Vaqtida topshirish', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='marketplace.order')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LevelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_level', models.IntegerField()),
                ('new_level', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daraja tarixi',
                'verbose_name_plural': 'Daraja tarixi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('first_job', '🎯 Birinchi ish'), ('five_jobs', '⭐ 5 ta ish'), ('perfect_rating', '💎 Mukammal reyting'), ('fast_delivery', '⚡ Tez yetkazish'), ('top_rated', '🏆 Top frilanser'), ('veteran', '👑 Veteran')], max_length=30)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nishon',
                'verbose_name_plural': 'Nishonlar',
                'unique_together': {('user', 'badge_type')},
            },
        ),
    ]
