# Generated by Django 4.2.29 on 2026-03-24 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_application_project_vacancy_and_more'),
        ('reputation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='order',
        ),
        migrations.AddField(
            model_name='review',
            name='vacancy',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='marketplace.vacancy'),
            preserve_default=False,
        ),
    ]
