# Generated by Django 4.2.29 on 2026-03-24 09:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_delete_order_vacancy_company_project_company_and_more'),
        ('reputation', '0002_remove_review_order_review_vacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Daraja tarixi'},
        ),
        migrations.RemoveField(
            model_name='review',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='review',
            name='project',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='marketplace.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('first_job', '🎯 Birinchi ish'), ('five_jobs', '⭐ 5 ta ish'), ('perfect_rating', '💎 Mukammal reyting'), ('fast_delivery', '⚡ Tez yetkazish'), ('top_rated', '🏆 Top worker'), ('veteran', '👑 Veteran')], max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='communication_score',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='deadline_score',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_score',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
