# Generated by Django 4.2.29 on 2026-03-26 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_application_options_alter_project_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reputation', '0004_alter_review_stars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Daraja tarixi', 'verbose_name_plural': 'Daraja tarixlari'},
        ),
        migrations.AlterField(
            model_name='review',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.project'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('project', 'reviewer', 'freelancer')},
        ),
    ]
