# Generated by Django 4.2.29 on 2026-03-24 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Mijoz'), ('freelancer', 'Frilanser')], default='freelancer', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True, help_text="Vergul bilan ajratilgan ko'nikmalar")),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('level', models.IntegerField(choices=[(1, 'Level 1 - Yangi'), (2, 'Level 2 - Professional'), (3, 'Level 3 - Expert')], default=1)),
                ('rating', models.FloatField(default=0.0)),
                ('completed_jobs_count', models.IntegerField(default=0)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profillar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('initial_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('final_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Ochiq'), ('IN_NEGOTIATION', 'Muzokaralar'), ('IN_PROGRESS', 'Jarayonda'), ('COMPLETED', 'Yakunlandi'), ('DELAYED', 'Kechikdi'), ('CANCELLED', 'Bekor qilindi')], default='OPEN', max_length=20)),
                ('category', models.CharField(choices=[('development', 'Dasturlash'), ('design', 'Dizayn'), ('writing', 'Yozuv'), ('marketing', 'Marketing'), ('video', 'Video'), ('audio', 'Audio'), ('translation', 'Tarjima'), ('other', 'Boshqa')], default='other', max_length=50)),
                ('required_skills', models.TextField(blank=True, help_text="Kerakli ko'nikmalar")),
                ('deadline_days', models.IntegerField(blank=True, null=True)),
                ('agreed_deadline', models.DateTimeField(blank=True, null=True)),
                ('description_embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_freelancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
