# Generated by Django 4.2.29 on 2026-03-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True)),
                ('proposed_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proposed_days', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('agreed_days', models.IntegerField()),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Jarayonda'), ('COMPLETED', 'Yakunlandi'), ('DELAYED', 'Kechikdi'), ('CANCELLED', 'Bekor')], default='IN_PROGRESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('development', 'Dasturlash'), ('design', 'Dizayn'), ('marketing', 'Marketing'), ('writing', 'Yozuv'), ('video', 'Video'), ('other', 'Boshqa')], default='other', max_length=50)),
                ('required_skills', models.TextField(blank=True)),
                ('budget_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deadline_days', models.IntegerField()),
                ('required_workers', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('OPEN', 'Ochiq'), ('IN_PROGRESS', 'Jarayonda'), ('CLOSED', 'Yopildi'), ('CANCELLED', 'Bekor'), ('COMPLETED', 'Yakunlandi')], default='OPEN', max_length=20)),
                ('is_team_project', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='assigned_freelancer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('client', 'Kompaniya'), ('freelancer', 'Worker')], default='freelancer', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
