# Generated by Django 4.2.29 on 2026-03-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_delete_order_vacancy_company_project_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
    ]
